import { initHostsSync } from '../hosts/check';
import { initLicenseSync } from '../license/sync';
import { initCoomeetMainWorldInject } from './coomeet-main-world-inject';
import { initDocumentVisibilitySpoof } from './document-visibility-spoof';
import { initFclcAlertSuppress, initFclcLinksGo } from '../sites/fclc';
import { initAnkergamesMainWorldInject } from '../sites/ankergames';
import { initAnygameMainWorldInject } from '../sites/anygame';
import { initApktealMainWorldInject } from '../sites/apkteal';
import { initFilecrExtractLink } from '../sites/filecr';
import { initFilecrRouteWatch } from '../sites/filecr/route-watch';
import { initFlightsimDownloadPatch } from '../sites/flightsim';
import { initShortxlinksBackground } from '../sites/shortxlinks';
import { initMultiup } from '../sites/multiup';
import { initCloverhubBackground } from '../sites/cloverhub';
import { initLootlabsMainWorldInject } from '../sites/lootlabs';
import { initXdmoviesMainWorldInject } from '../sites/xdmovies/mediator-page';
import { initArolinksBackground } from '../sites/arolinks';
import { initTipsguruCookieDest } from '../sites/tipsguru';
import { initExeioAdblockInject } from '../sites/exeio';
import { initFilecryptPowInject } from '../sites/filecrypt';
import { initLksfyAdblockInject } from '../sites/lksfy';
import { initRinkuFlowWatch } from '../sites/rinku';
import { initCutyGoUnlockInject, initCutyQuickRedirect } from '../sites/cuty';
import { initStorylineScormMainWorldInject } from '../sites/storyline-scorm';
import { initLink4mRedirect } from '../sites/tech8s';
import { initOceanofgamesResolve } from '../sites/oceanofgames';
import { initGapkmodResolve } from '../sites/gapkmod';
import { initGetmodsapkMainWorldInject } from '../sites/getmodsapk';
import { initApkvisionMainWorldInject } from '../sites/apkvision';
import { initApkawardMainWorldInject } from '../sites/apkaward';
import { initFuzyapkMainWorldInject } from '../sites/fuzyapk';
import { initModdroidMainWorldInject } from '../sites/moddroid';
import { initModded1MainWorldInject } from '../sites/modded-1';
import { initModsmaniacMainWorldInject } from '../sites/modsmaniac';
import { initDevuploadsResolve } from '../sites/devuploads';
import { initDuploadHoldNav, initDuploadResolve } from '../sites/dupload';
import { initStreamerviewerbotMainWorldInject } from '../sites/streamerviewerbot';
import { initWorkinkMainWorldInject } from '../sites/workink';
import { initVexfileMainWorldInject } from '../sites/vexfile';
import { initDlsurfMainWorldInject } from '../sites/dlsurf';
import { initAlpharedeBackground } from '../sites/alpharede';
import { initEarnlinksBackground } from '../sites/earnlinks';
import { initShrinkpeBackground } from '../sites/shrinkpe';
import { initSflBackground } from '../sites/sfl';
import { initLiteshortBackground } from '../sites/liteshort';
import { initNitrolinkBackground } from '../sites/nitrolink';
import { initVexolinkBackground } from '../sites/vexolink';
import { initUnlocktoearnBackground } from '../sites/unlocktoearn';
import { initCpmlinkNetAdblockInject } from '../sites/cpmlink-net';

initCoomeetMainWorldInject();
initDocumentVisibilitySpoof();
initFclcAlertSuppress();
initFclcLinksGo();
initAnkergamesMainWorldInject();
initAnygameMainWorldInject();
initApktealMainWorldInject();
initFilecrExtractLink();
initFilecrRouteWatch();
initFlightsimDownloadPatch();
initShortxlinksBackground();
initMultiup();
initLink4mRedirect();
initLootlabsMainWorldInject();
initCloverhubBackground();
initXdmoviesMainWorldInject();
initArolinksBackground();
initTipsguruCookieDest();
initExeioAdblockInject();
initFilecryptPowInject();
initLksfyAdblockInject();
initRinkuFlowWatch();
initCutyGoUnlockInject();
initCutyQuickRedirect();
initStorylineScormMainWorldInject();
initStreamerviewerbotMainWorldInject();
initWorkinkMainWorldInject();
initOceanofgamesResolve();
initGapkmodResolve();
initGetmodsapkMainWorldInject();
initApkvisionMainWorldInject();
initApkawardMainWorldInject();
initFuzyapkMainWorldInject();
initModdroidMainWorldInject();
initModded1MainWorldInject();
initModsmaniacMainWorldInject();
initDevuploadsResolve();
initDuploadHoldNav();
initDuploadResolve();
initVexfileMainWorldInject();
initDlsurfMainWorldInject();
initAlpharedeBackground();
initEarnlinksBackground();
initShrinkpeBackground();
initSflBackground();
initLiteshortBackground();
initNitrolinkBackground();
initVexolinkBackground();
initUnlocktoearnBackground();
initCpmlinkNetAdblockInject();
initHostsSync();
initLicenseSync();
